export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const LOGGED_USER_ORDER_REQUEST = "LOGGED_USER_ORDER_REQUEST";
export const LOGGED_USER_ORDER_SUCCESS = "LOGGED_USER_ORDER_SUCCESS";
export const LOGGED_USER_ORDER_FAIL = "LOGGED_USER_ORDER_FAIL";